# Generated by Django 3.1.7 on 2021-04-02 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField(max_length=200)),
                ('ciudadResidencia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aerolinea', models.CharField(max_length=200)),
                ('costo', models.IntegerField()),
                ('NoCupos', models.IntegerField()),
                ('fechaSalida', models.DateField(max_length=200)),
                ('fechaLlegada', models.DateField(max_length=200)),
                ('horaSalida', models.TimeField(max_length=200)),
                ('horaLlegada', models.TimeField(max_length=200)),
                ('LugarSalida', models.CharField(max_length=200)),
                ('Destino', models.CharField(max_length=200)),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['aerolinea'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHoraReserva', models.DateTimeField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuluayork.cliente')),
                ('idFuncionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuluayork.usuario')),
                ('idVuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuluayork.vuelos')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='idVuelo',
            field=models.ManyToManyField(null=True, to='Tuluayork.Vuelos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuluayork.usuario'),
        ),
    ]
