# Generated by Django 3.1.7 on 2021-04-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuluayork', '0002_auto_20210402_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
